name = "hugo-theme-console-tokyo-night"
license = "MIT"
licenselink = "https://github.com/adegoodyer/hugo-theme-console-tokyo-night/blob/master/LICENSE"
description = "Minimal terminal styled Hugo theme with colour scheme based on Tokyo Night."
homepage = "https://github.com/adegoodyer/hugo-theme-console-tokyo-night"

[author]
  name = "Ade Goodyer"
  homepage = "https://adegoodyer.com"
  github = "https://github.com/adegoodyer"

[original]
  name = "Marcin Mierzejewski"
  homepage = "https://mrmierzejewski.com"
  github = "https://github.com/mrmierzejewski"

[original]
  author = "Jonas D."
  homepage = "https://terminalcss.xyz/"
  repo = "https://github.com/Gioni06/terminal.css"
